import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import FooterLayouts from "@/components/layouts/FooterLayouts";
import ChatLayouts from "@/components/layouts/ChatLayouts";
import MenuLayouts from "@/components/layouts/MenuLayouts";

export const metadata: Metadata = {
  title: {
    default: "Gaffistore",
    template: "%s | GFS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=JetBrains Mono"
        />
      </head>
      <body>
        <AntdRegistry>
          <MenuLayouts />
          {children}
          <FooterLayouts />
          <ChatLayouts />
        </AntdRegistry>
      </body>
    </html>
  );
}
